---
- name: Retrieve ARP table
  hosts: all
  gather_facts: false

  tasks:
    - name: show arp
      raw: "show arp"
      register: print_output

    - debug: var=print_output.stdout_lines

# Commands to run: 0) nano getarp1.yml
#1) ansible-playbook getarp1.yml -u user -k
#2) Grep for MAC address: ansible-playbook getarp1.yml -u user -k | grep 'ok:\|4700'
#3) Grep for IP address: ansible-playbook getarp1.yml -u user -k | grep 'ok:\|100.51'