---
- name: Configure HTTP-Pool with Priority Group Settings
  hosts: F5
  connection: local
  gather_facts: no

  vars:
    bigip_host: F5-1
    bigip_admin: "admin"
    bigip_password: "Abc@Admin1"
    provider:
      server: "{{ bigip_host }}"
      user: "{{ bigip_admin }}"
      password: "{{ bigip_password }}"
      validate_certs: no
      server_port: 443

  tasks:
    - name: Update priority group settings of existing pool members
      bigip_pool_member:
        pool: "HTTP-Pool"
        partition: "Common"
        fqdn: "{{ item.fqdn }}"
        port: "{{ item.port | default(80) }}"
        priority_group: "{{ item.priority_group }}"
        state: "present"
        provider: "{{ provider }}"
      loop:
        - { fqdn: "/Common/Server-1", priority_group: 10 }
        - { fqdn: "/Common/Server-2", priority_group: 10 }
        - { fqdn: "/Common/Server-3", priority_group: 10 }
        - { fqdn: "/Common/Server-4", priority_group: 5 }
        - { fqdn: "/Common/Server-5", priority_group: 5 }
      delegate_to: localhost
